apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/hekonsek/demo-4354tr4rt4r:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/hekonsek/demo-4354tr4rt4r:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: demo-4354tr4rt4r
        chartPath: charts/demo-4354tr4rt4r
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/hekonsek/demo-4354tr4rt4r"
          image.tag: "{{.TAG}}"
